spring:
  datasource:
    url: jdbc:h2:~/cafe-kiosk
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update #실행할때마다 테이블 새로 생성
    properties:
      hibernate:
        format_sql: true
    show-sql: true    #실행되는 SQL 콘솔에 출력

  h2:
    console:
      enabled: true   #브라우저에서 H2콘솔 접속가능
      path: /h2-console